export const Types = {
  SET_SORT_BY: 'SET_SORT_BY',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_PIZZAS: 'SET_PIZZAS',
  SET_LOADED_PIZZAS: 'SET_LOADED_PIZZAS',
  ADD_PIZZA_TO_CART: 'ADD_PIZZA_TO_CART',
  REMOVE_PIZZA_TO_CART: 'REMOVE_PIZZA_TO_CART',
  CLEAR_CART: 'CLEAR_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  PLUS_CART_ITEM: 'PLUS_CART_ITEM',
  MINUS_CART_ITEM: 'MINUS_CART_ITEM',
};
