export const Types = {
  SET_SORT_BY: 'SET_SORT_BY',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_PIZZAS: 'SET_PIZZAS',
  SET_LOADED_PIZZAS: 'SET_LOADED_PIZZAS',
  SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
  SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
  ADD_PIZZA_TO_CART: 'ADD_PIZZA_TO_CART',
};
